/* 389. Find the Difference */
/** Given two strings s and t which consist of only lowercase letters.
 *  String t is generated by random shuffling string s and then add one more letter at a random position.
 *  Find the letter that was added in t.
 * 
 *  Example:
 *  Input:
 *  s = "abcd"
 *  t = "abcde"
 * 
 *  Output: e
 *  Explanation: 'e' is the letter that was added. **/

#include <string>
#include <iostream>

using namespace std;
 
char findTheDifference(string s, string t) {
    int firstSum = 0;
    int secondSum = 0;

    for (int i=0; i < s.length(); ++i) {
        firstSum += s[i];
    }

    for (int i=0; i < t.length(); ++i) {
        secondSum += t[i];
    }

    return (char)(secondSum-firstSum);
}

int main() {
    string s = "abcd";
    string t = "abcde";
    char answer = findTheDifference(s,t);

    cout << answer << endl;
    return 0;
}